apiVersion: apps/v1
kind: Deployment
metadata:
  name: igdb-telegram-bot
  labels:
    app: igdb-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igdb-telegram-bot
  template:
    metadata:
      labels:
        app: igdb-telegram-bot
    spec:
      containers:
        - name: igdb-telegram-bot
          image: ghcr.io/jorgemontes/igdb-telegram-bot:master
          volumeMounts:
            - name: cm-igdb-telegram-inline-bot
              mountPath: "/etc/cm"
              readOnly: true
      imagePullSecrets:
        - name: docker-registry-ghcr
      volumes:
        - name: cm-igdb-telegram-inline-bot

