apiVersion: apps/v1
kind: Deployment
metadata:
  name: igdb-telegram-bot
  labels:
    app: igdb-telegram-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: igdb-telegram-bot
  template:
    metadata:
      labels:
        app: igdb-telegram-bot
    spec:
      containers:
        - name: igdb-telegram-bot
          image: ghcr.io/jorgemontes/igdb-telegram-bot:master
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: cm-igdb-telegram-inline-bot
                  key: BOT_TOKEN
            - name: TWITCH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: cm-igdb-telegram-inline-bot
                  key: TWITCH_CLIENT_ID
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: cm-igdb-telegram-inline-bot
                  key: TWITCH_CLIENT_SECRET
            - name: CALL_BACK_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-igdb-telegram-inline-bot
                  key: CALL_BACK_URL
      imagePullSecrets:
        - name: docker-registry-ghcr
      volumes:
        - name: cm-igdb-telegram-inline-bot

