apiVersion: v1
kind: Service
metadata:
  name: igdb-telegram-bot-service
spec:
  type: NodePort
  selector:
    app: igdb-telegram-bot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32304